# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(636, 478)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setMinimumSize(QtCore.QSize(636, 377))
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, -1, 617, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelLoadedImage = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelLoadedImage.setMaximumSize(QtCore.QSize(16777215, 50))
        self.labelLoadedImage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLoadedImage.setObjectName("labelLoadedImage")
        self.verticalLayout_5.addWidget(self.labelLoadedImage)
        self.frameLoadedImage = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frameLoadedImage.setMinimumSize(QtCore.QSize(0, 200))
        self.frameLoadedImage.setFrameShape(QtWidgets.QFrame.Box)
        self.frameLoadedImage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLoadedImage.setObjectName("frameLoadedImage")
        self.label = QtWidgets.QLabel(self.frameLoadedImage)
        self.label.setGeometry(QtCore.QRect(0, 0, 281, 321))
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.frameLoadedImage)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.launchTreatment = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.launchTreatment.setMaximumSize(QtCore.QSize(50, 16777215))
        self.launchTreatment.setObjectName("launchTreatment")
        self.horizontalLayout_2.addWidget(self.launchTreatment)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelResultedImage = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelResultedImage.setMaximumSize(QtCore.QSize(16777215, 50))
        self.labelResultedImage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelResultedImage.setObjectName("labelResultedImage")
        self.verticalLayout_4.addWidget(self.labelResultedImage)
        self.frameResultedImage = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frameResultedImage.setMinimumSize(QtCore.QSize(0, 200))
        self.frameResultedImage.setFrameShape(QtWidgets.QFrame.Box)
        self.frameResultedImage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameResultedImage.setObjectName("frameResultedImage")
        self.labelResult = QtWidgets.QLabel(self.frameResultedImage)
        self.labelResult.setGeometry(QtCore.QRect(0, 0, 281, 321))
        self.labelResult.setText("")
        self.labelResult.setObjectName("labelResult")
        self.verticalLayout_4.addWidget(self.frameResultedImage)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.CapturePhoto = QtWidgets.QPushButton(self.centralWidget)
        self.CapturePhoto.setGeometry(QtCore.QRect(140, 380, 89, 25))
        self.CapturePhoto.setObjectName("CapturePhoto")
        self.PlayPhotoButton = QtWidgets.QPushButton(self.centralWidget)
        self.PlayPhotoButton.setGeometry(QtCore.QRect(270, 380, 89, 25))
        self.PlayPhotoButton.setObjectName("PlayPhotoButton")
        self.CancelButton = QtWidgets.QPushButton(self.centralWidget)
        self.CancelButton.setGeometry(QtCore.QRect(400, 380, 89, 25))
        self.CancelButton.setObjectName("CancelButton")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 636, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFichier = QtWidgets.QMenu(self.menuBar)
        self.menuFichier.setObjectName("menuFichier")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.openFile = QtWidgets.QAction(MainWindow)
        self.openFile.setObjectName("openFile")
        self.menuFichier.addAction(self.openFile)
        self.menuBar.addAction(self.menuFichier.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scan3D"))
        self.labelLoadedImage.setText(_translate("MainWindow", "INPUT"))
        self.launchTreatment.setText(_translate("MainWindow", "2D"))
        self.labelResultedImage.setText(_translate("MainWindow", "OUTPUT"))
        self.CapturePhoto.setText(_translate("MainWindow", "Capture"))
        self.PlayPhotoButton.setText(_translate("MainWindow", "Launch"))
        self.CancelButton.setText(_translate("MainWindow", "Cancel"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.openFile.setText(_translate("MainWindow", "Ouvrir une image..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

